// AUTO-GENERATED by web/scripts/capture-mock-fixtures.ts
// Do not edit by hand. Re-run the script when the ads expire.

import type { MockScript } from '@/features/mock/scripts/types'

export const compareThreeRolesScript: MockScript = {
  prompt: 'Compare two top machine learning roles side by side',
  chipLabel: 'Compare two top machine learning roles side by side',
  messageId: 'mock-message-compare',
  profile:
    '# Profile\n\n- Senior AI engineer, 8 years experience\n- Strong in Python, PyTorch, Hugging Face, retrieval-augmented generation\n- Comfortable with production MLOps on AWS or GCP\n- Based in Stockholm, open to hybrid\n',
  steps: [
    {
      kind: 'text',
      content:
        'Pulling a fresh batch of machine learning engineer roles so the comparison has live candidates.',
    },
    {
      kind: 'tool',
      toolName: 'searchJobs',
      toolCallId: 'mock-compare-roles-call-1',
      input: {
        query: 'machine learning engineer',
        top_k: 5,
      },
      output: {
        results: [
          {
            ad_id: '31343756',
            headline: 'Machine Learning Engineer ',
            employer_name: 'Modulai AB',
            municipality: 'Stockholm',
            application_deadline: '2027-02-11T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31343756',
            description_excerpt:
              'Modulai works with fish, trains, clothes, money, pets, office spaces, sound sensors and much more. If there is data, we do ML (Machine Learning) on it. Our team consists of devoted ML engineers with strong track records from some of Sweden’s most successful startups. We work on project basis and take end-to-end responsibility. We love ML and we think that the best way for us to expand our knowledge is to be exposed to a diversified set of challenging and fun projects. MACHINE…',
            occupation_label: 'Civilingenjör, systemutveckling',
          },
          {
            ad_id: '31355712',
            headline: 'Machine Learning Engineer',
            employer_name: 'Lorex Labs AB',
            municipality: 'Stockholm',
            application_deadline: '2026-09-13T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31355712',
            description_excerpt:
              'Company Description: Lorex Labs specializes in verification, validation, and value optimization for unique AI solutions. The company helps organizations build AI systems that outperform competitors by focusing on measurable impact and trustworthiness. Lorex Labs supports clients in accelerating development velocity and improving the reliability of machine learning models. By unlocking actionable insights, the company enables real-world performance gains across diverse AI appl…',
            occupation_label: 'Systemutvecklare/Programmerare',
          },
          {
            ad_id: '31226420',
            headline: 'Machine Learning Engineer',
            employer_name: 'Nextory AB',
            municipality: 'Stockholm',
            application_deadline: '2026-12-26T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31226420',
            description_excerpt:
              'You know that bit where every company says they’re “changing the world”? Yeah, it can feel a little forced. But we like to think our story actually has some realness to it. Our story begins with Shadi Bitar and Ninos Malki, who came to Sweden from Syria as kids and discovered that books could be a bridge - helping them learn the language, understand the culture, and explore new worlds. A thought emerged, what if everyone could have that? And just like that, Nextory was born -…',
            occupation_label: 'Backend-utvecklare',
          },
        ],
      },
    },
    {
      kind: 'text',
      content:
        ' Comparing the two strongest candidates. The first is Machine Learning Engineer and the second is Machine Learning Engineer.',
    },
    {
      kind: 'tool',
      toolName: 'compareRoles',
      toolCallId: 'mock-compare-roles-call-2',
      input: {
        ad_ids: ['31343756', '31355712'],
      },
      output: {
        results: [
          {
            ad_id: '31343756',
            headline: 'Machine Learning Engineer ',
            employer_name: 'Modulai AB',
            municipality: 'Stockholm',
            application_deadline: '2027-02-11T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31343756',
            description_excerpt:
              'Modulai works with fish, trains, clothes, money, pets, office spaces, sound sensors and much more. If there is data, we do ML (Machine Learning) on it. Our team consists of devoted ML engineers with strong track records from some of Sweden’s most successful startups. We work on project basis and take end-to-end responsibility. We love ML and we think that the best way for us to expand our knowledge is to be exposed to a diversified set of challenging and fun projects. MACHINE…',
            occupation_label: 'Civilingenjör, systemutveckling',
          },
          {
            ad_id: '31355712',
            headline: 'Machine Learning Engineer',
            employer_name: 'Lorex Labs AB',
            municipality: 'Stockholm',
            application_deadline: '2026-09-13T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31355712',
            description_excerpt:
              'Company Description: Lorex Labs specializes in verification, validation, and value optimization for unique AI solutions. The company helps organizations build AI systems that outperform competitors by focusing on measurable impact and trustworthiness. Lorex Labs supports clients in accelerating development velocity and improving the reliability of machine learning models. By unlocking actionable insights, the company enables real-world performance gains across diverse AI appl…',
            occupation_label: 'Systemutvecklare/Programmerare',
          },
        ],
      },
    },
    {
      kind: 'tool',
      toolName: 'pairAdsForCompare',
      toolCallId: 'mock-compare-roles-call-3',
      input: {
        ad_id_a: '31343756',
        ad_id_b: '31355712',
        diffs: [
          {
            field: 'Employer',
            a: 'Modulai AB',
            b: 'Lorex Labs AB',
            verdict: 'neither',
          },
          {
            field: 'Location',
            a: 'Stockholm',
            b: 'Stockholm',
            verdict: 'neither',
          },
          {
            field: 'Deadline',
            a: '2027-02-11',
            b: '2026-09-13',
            verdict: 'a',
          },
        ],
      },
      output: {
        accepted: true,
        ad_id_a: '31343756',
        ad_id_b: '31355712',
        diffs: [
          {
            field: 'Employer',
            a: 'Modulai AB',
            b: 'Lorex Labs AB',
            verdict: 'neither',
          },
          {
            field: 'Location',
            a: 'Stockholm',
            b: 'Stockholm',
            verdict: 'neither',
          },
          {
            field: 'Deadline',
            a: '2027-02-11',
            b: '2026-09-13',
            verdict: 'a',
          },
        ],
      },
    },
    {
      kind: 'text',
      content:
        ' Compare view is up on the canvas. A third candidate from Nextory AB is also in the result set. Ask for a pair against it for a deeper bake-off.',
    },
  ],
} as const
