// AUTO-GENERATED by web/scripts/capture-mock-fixtures.ts
// Do not edit by hand. Re-run the script when the ads expire.

import type { MockScript } from '@/features/mock/scripts/types'

export const compareThreeRolesScript: MockScript = {
  prompt: 'Compare two top machine learning roles side by side',
  chipLabel: 'Compare two top machine learning roles side by side',
  messageId: 'mock-message-compare',
  profile:
    '# Profile\n\n- Senior AI engineer, 8 years experience\n- Strong in Python, PyTorch, Hugging Face, retrieval-augmented generation\n- Comfortable with production MLOps on AWS or GCP\n- Based in Stockholm, open to hybrid\n',
  steps: [
    {
      kind: 'text',
      content:
        'Pulling a fresh batch of machine learning engineer roles so the comparison has live candidates.',
    },
    {
      kind: 'tool',
      toolName: 'searchJobs',
      toolCallId: 'mock-compare-roles-call-1',
      input: {
        query: 'machine learning engineer',
        top_k: 5,
      },
      output: {
        results: [
          {
            ad_id: '30991390',
            headline: 'Machine Learning Engineer',
            employer_name: 'Einride AB (publ)',
            municipality: 'Göteborg',
            application_deadline: '2026-05-14T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/30991390',
            description_excerpt:
              'We are growing our team and looking for a skilled and passionate Machine Learning Engineer within in multi-modal perception systems for autonomous driving applications. The ideal candidate has strong software engineering skills and experience in designing, developing and transitioning R&D solutions into final products. You will: Research and develop state-of-the-art machine learning/deep learning models and architectures to advance our perception stack Develop machine learnin…',
            occupation_label: 'Mjukvaruutvecklare',
          },
          {
            ad_id: '30916616',
            headline: 'Machine Learning Engineer',
            employer_name: 'Sellhelp AB',
            municipality: 'Stockholm',
            application_deadline: '2026-06-30T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/30916616',
            description_excerpt:
              'Leverage the power of AI to revolutionize sustainable shopping for millions of customers. 💙 Sellpy’s vision is to empower everyone to live circularly. We believe that every item deserves a second life, and we see huge financial, social and environmental value in making sure this happens. Join us in building technology that drives real change. Machine Learning at Sellpy We look for you who want to be part of our journey to make sustainable shopping the first-hand choice by bu…',
            occupation_label: 'Systemutvecklare/Programmerare',
          },
          {
            ad_id: '30646235',
            headline: 'Machine Learning Engineer ',
            employer_name: 'Modulai AB',
            municipality: 'Stockholm',
            application_deadline: '2026-08-20T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/30646235',
            description_excerpt:
              'Modulai works with fish, trains, clothes, money, pets, office spaces, sound sensors and much more. If there is data, we do ML (Machine Learning) on it. Our team consists of devoted ML engineers with strong track records from some of Sweden’s most successful startups. We work on project basis and take end-to-end responsibility. We love ML and we think that the best way for us to expand our knowledge is to be exposed to a diversified set of challenging and fun projects. MACHINE…',
            occupation_label: 'Civilingenjör, systemutveckling',
          },
        ],
      },
    },
    {
      kind: 'text',
      content:
        ' Comparing the two strongest candidates. The first is Machine Learning Engineer and the second is Machine Learning Engineer.',
    },
    {
      kind: 'tool',
      toolName: 'compareRoles',
      toolCallId: 'mock-compare-roles-call-2',
      input: {
        ad_ids: ['30991390', '30916616'],
      },
      output: {
        results: [
          {
            ad_id: '30991390',
            headline: 'Machine Learning Engineer',
            employer_name: 'Einride AB (publ)',
            municipality: 'Göteborg',
            application_deadline: '2026-05-14T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/30991390',
            description_excerpt:
              'We are growing our team and looking for a skilled and passionate Machine Learning Engineer within in multi-modal perception systems for autonomous driving applications. The ideal candidate has strong software engineering skills and experience in designing, developing and transitioning R&D solutions into final products. You will: Research and develop state-of-the-art machine learning/deep learning models and architectures to advance our perception stack Develop machine learnin…',
            occupation_label: 'Mjukvaruutvecklare',
          },
          {
            ad_id: '30916616',
            headline: 'Machine Learning Engineer',
            employer_name: 'Sellhelp AB',
            municipality: 'Stockholm',
            application_deadline: '2026-06-30T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/30916616',
            description_excerpt:
              'Leverage the power of AI to revolutionize sustainable shopping for millions of customers. 💙 Sellpy’s vision is to empower everyone to live circularly. We believe that every item deserves a second life, and we see huge financial, social and environmental value in making sure this happens. Join us in building technology that drives real change. Machine Learning at Sellpy We look for you who want to be part of our journey to make sustainable shopping the first-hand choice by bu…',
            occupation_label: 'Systemutvecklare/Programmerare',
          },
        ],
      },
    },
    {
      kind: 'tool',
      toolName: 'pairAdsForCompare',
      toolCallId: 'mock-compare-roles-call-3',
      input: {
        ad_id_a: '30991390',
        ad_id_b: '30916616',
        diffs: [
          {
            field: 'Employer',
            a: 'Einride AB (publ)',
            b: 'Sellhelp AB',
            verdict: 'neither',
          },
          {
            field: 'Location',
            a: 'Göteborg',
            b: 'Stockholm',
            verdict: 'neither',
          },
          {
            field: 'Deadline',
            a: '2026-05-14',
            b: '2026-06-30',
            verdict: 'b',
          },
        ],
      },
      output: {
        accepted: true,
        ad_id_a: '30991390',
        ad_id_b: '30916616',
        diffs: [
          {
            field: 'Employer',
            a: 'Einride AB (publ)',
            b: 'Sellhelp AB',
            verdict: 'neither',
          },
          {
            field: 'Location',
            a: 'Göteborg',
            b: 'Stockholm',
            verdict: 'neither',
          },
          {
            field: 'Deadline',
            a: '2026-05-14',
            b: '2026-06-30',
            verdict: 'b',
          },
        ],
      },
    },
    {
      kind: 'text',
      content:
        ' Compare view is up on the canvas. A third candidate from Modulai AB is also in the result set. Ask for a pair against it for a deeper bake-off.',
    },
  ],
} as const
