// AUTO-GENERATED by web/scripts/capture-mock-fixtures.ts
// Do not edit by hand. Re-run the script when the ads expire.

import type { MockScript } from '@/features/mock/scripts/types'

export const deadlineTimelineScript: MockScript = {
  prompt: 'Which AI roles are closing in the next two weeks',
  chipLabel: 'Which AI roles are closing in the next two weeks',
  messageId: 'mock-message-deadline',
  profile:
    '# Profile\n\n- Senior AI engineer, 8 years experience\n- Strong in Python, PyTorch, Hugging Face, retrieval-augmented generation\n- Comfortable with production MLOps on AWS or GCP\n- Based in Stockholm, open to hybrid\n',
  steps: [
    {
      kind: 'text',
      content:
        'Pulling AI engineering ads whose application deadline lands inside the next two weeks.',
    },
    {
      kind: 'tool',
      toolName: 'deadlineWatch',
      toolCallId: 'mock-deadline-ai-call-1',
      input: {
        window_days: 14,
        top_k: 5,
      },
      output: {
        results: [
          {
            ad_id: '31429468',
            headline: 'Fullstack AI Engineer',
            employer_name: 'Avaron AB',
            municipality: 'Malmö',
            application_deadline: '2026-09-09T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31429468',
            days_until_deadline: 3,
          },
          {
            ad_id: '31440715',
            headline: 'Graduate AI Engineer - ADAS AI Agents',
            employer_name: 'Luxoft Sweden AB',
            municipality: 'Göteborg',
            application_deadline: '2026-09-14T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31440715',
            days_until_deadline: 8,
          },
          {
            ad_id: '31427836',
            headline: 'Senior Forward Deployed AI Engineer',
            employer_name: 'Nordea Bank Abp, filial i Sverige',
            municipality: 'Stockholm',
            application_deadline: '2026-09-20T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31427836',
            days_until_deadline: 14,
          },
          {
            ad_id: '31379145',
            headline: 'AI Engineer - Euromaster',
            employer_name: 'EUROMASTER AKTIEBOLAG',
            municipality: 'Varberg',
            application_deadline: '2026-09-21T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31379145',
            days_until_deadline: 15,
          },
          {
            ad_id: '31417598',
            headline: 'Embedded AI Engineer, Lund',
            employer_name: 'Axis Communications Aktiebolag',
            municipality: 'Lund',
            application_deadline: '2026-09-21T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31417598',
            days_until_deadline: 15,
          },
        ],
      },
    },
    {
      kind: 'tool',
      toolName: 'placeAdsOnTimeline',
      toolCallId: 'mock-deadline-ai-call-2',
      input: {
        ad_ids: ['31429468', '31440715', '31427836', '31379145', '31417598'],
        today_cursor: '2026-09-07',
      },
      output: {
        accepted: true,
        ad_ids: ['31429468', '31440715', '31427836', '31379145', '31417598'],
        today_cursor: '2026-09-07',
      },
    },
    {
      kind: 'text',
      content:
        ' 5 roles laid on the date axis. The soonest is Fullstack AI Engineer at Avaron AB, 3 days out.',
    },
  ],
} as const
