// AUTO-GENERATED by web/scripts/capture-mock-fixtures.ts
// Do not edit by hand. Re-run the script when the ads expire.

import type { MockScript } from '@/features/mock/scripts/types'

export const deadlineTimelineScript: MockScript = {
  prompt: 'Which AI roles are closing in the next two weeks',
  chipLabel: 'Which AI roles are closing in the next two weeks',
  messageId: 'mock-message-deadline',
  profile:
    '# Profile\n\n- Senior AI engineer, 8 years experience\n- Strong in Python, PyTorch, Hugging Face, retrieval-augmented generation\n- Comfortable with production MLOps on AWS or GCP\n- Based in Stockholm, open to hybrid\n',
  steps: [
    {
      kind: 'text',
      content:
        'Pulling AI engineering ads whose application deadline lands inside the next two weeks.',
    },
    {
      kind: 'tool',
      toolName: 'deadlineWatch',
      toolCallId: 'mock-deadline-ai-call-1',
      input: {
        window_days: 14,
        top_k: 5,
      },
      output: {
        results: [
          {
            ad_id: '31261053',
            headline: 'Embedded AI Engineer, Lund',
            employer_name: 'AXIS COMMUNICATIONS AKTIEBOLAG',
            municipality: 'Lund',
            application_deadline: '2026-08-06T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31261053',
            days_until_deadline: 4,
          },
          {
            ad_id: '31290812',
            headline: 'AI Enablement Engineer',
            employer_name: 'Extenda Retail AB',
            municipality: 'Solna',
            application_deadline: '2026-08-10T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31290812',
            days_until_deadline: 8,
          },
          {
            ad_id: '31288284',
            headline: 'Founding AI Engineer',
            employer_name: 'Spiich Labs AB',
            municipality: 'Stockholm',
            application_deadline: '2026-08-21T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31288284',
            days_until_deadline: 19,
          },
        ],
      },
    },
    {
      kind: 'tool',
      toolName: 'placeAdsOnTimeline',
      toolCallId: 'mock-deadline-ai-call-2',
      input: {
        ad_ids: ['31261053', '31290812', '31288284'],
        today_cursor: '2026-08-03',
      },
      output: {
        accepted: true,
        ad_ids: ['31261053', '31290812', '31288284'],
        today_cursor: '2026-08-03',
      },
    },
    {
      kind: 'text',
      content:
        ' 3 roles laid on the date axis. The soonest is Embedded AI Engineer, Lund at AXIS COMMUNICATIONS AKTIEBOLAG, 4 days out.',
    },
  ],
} as const
