// AUTO-GENERATED by web/scripts/capture-mock-fixtures.ts
// Do not edit by hand. Re-run the script when the ads expire.

import type { MockScript } from '@/features/mock/scripts/types'

export const stockholmAiEngineeringScript: MockScript = {
  prompt: 'Show me Stockholm AI engineering roles',
  chipLabel: 'Show me Stockholm AI engineering roles',
  messageId: 'mock-message-sthlm-ai',
  profile:
    '# Profile\n\n- Senior AI engineer, 8 years experience\n- Strong in Python, PyTorch, Hugging Face, retrieval-augmented generation\n- Comfortable with production MLOps on AWS or GCP\n- Based in Stockholm, open to hybrid\n',
  steps: [
    {
      kind: 'text',
      content:
        'Looking up the JobTech taxonomy for AI engineering and Stockholm so the search query uses real concept ids.',
    },
    {
      kind: 'tool',
      toolName: 'lookupConcept',
      toolCallId: 'mock-sthlm-ai-call-1',
      input: {
        query: 'AI engineer Stockholm',
        top_k: 6,
      },
      output: {
        results: [
          {
            concept_id: 'hCMr_L4F_8hq',
            preferred_label: 'SQE Supplier Quality Engineer',
            type: 'occupation',
          },
          {
            concept_id: 'CifL_Rzy_Mku',
            preferred_label: 'Stockholms län',
            type: 'region',
          },
        ],
      },
    },
    {
      kind: 'text',
      content:
        ' Now searching live JobTech ads for AI engineering roles based in Stockholm.',
    },
    {
      kind: 'tool',
      toolName: 'searchJobs',
      toolCallId: 'mock-sthlm-ai-call-2',
      input: {
        query: 'AI engineer',
        top_k: 5,
      },
      output: {
        results: [
          {
            ad_id: '30991050',
            headline: 'AI Engineer',
            employer_name: 'Umain AB',
            municipality: 'Stockholm',
            application_deadline: '2026-10-31T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/30991050',
            description_excerpt:
              "At Umain, we're not just creating software; we're crafting the future, one innovative project at a time. With our motto \"Shape, Ship, Scale,\" we empower our team to not only envision the future but also play a pivotal role in building it. We're a dynamic team where you can shape the future, ship groundbreaking solutions, and scale your abilities in many different ways. We're on the lookout for developers ready to join us in this journey, bringing passion, creativity, and dedi…",
            occupation_label: 'Mjukvaruutvecklare',
          },
          {
            ad_id: '31290812',
            headline: 'AI Enablement Engineer',
            employer_name: 'Extenda Retail AB',
            municipality: 'Solna',
            application_deadline: '2026-08-10T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31290812',
            description_excerpt:
              'We are looking for an AI Enablement Engineer. Your mission is to develop and improve our AI capabilities, and make these available across the company. As an AI Enablement Engineer, you will work with the design, implementation, and scaling of AI architecture and solutions. You will follow industry trends connecting the potential of AI with organizational functions. Working closely with senior stakeholders and cross-functional teams, you will ensure that technical solutions al…',
            occupation_label: 'Mjukvaruutvecklare',
          },
          {
            ad_id: '31288284',
            headline: 'Founding AI Engineer',
            employer_name: 'Spiich Labs AB',
            municipality: 'Stockholm',
            application_deadline: '2026-08-21T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31288284',
            description_excerpt:
              "TL;DR We're looking for a founding AI Engineer to help build the AI colleague every sales professional wishes they had. You'll own the agent stack end-to-end - from model selection to database (knowledge graph) structure and search algorithm development. Must be curious, experimental, and obsessed with agentic systems. Why join We’re a small, talent-dense team of engineers building a generation-defining company from Stockholm. We value speed, rigour, and extreme ownership. If…",
            occupation_label: 'Dataingenjör',
          },
          {
            ad_id: '31284834',
            headline: 'AI Enablement Engineer',
            employer_name: 'Xensam AB',
            municipality: 'Stockholm',
            application_deadline: '2027-01-16T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31284834',
            description_excerpt:
              'Xensam: Join the Future of SAM Xensam is the leader in AI-powered, cloud-based Software Asset Management. Our technology brings clarity to complex IT environments, helping users make smart, data-driven decisions and maximize software ROI. Recognized with the Highest Growth Award and ranked #3 Overall Champion at the Main Software 50 Awards Nordics, we’re scaling fast and looking for people who want to join the journey. At Xensam, you play a key role in a team built on energy,…',
            occupation_label: 'Backend-utvecklare',
          },
          {
            ad_id: '31256366',
            headline: 'Senior AI Engineer',
            employer_name: 'Workday Sweden Aktiebolag',
            municipality: 'Stockholm',
            application_deadline: '2027-01-01T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31256366',
            description_excerpt:
              'Sana is an AI lab building superintelligence for work. We believe organizations can accomplish their missions faster when teams can effortlessly access knowledge, automate repetitive work, and learn anything with the help of agentic AI. As part of Workday, we are committed to building AI that augments people - not replaces them. We bring this mission to life through two products. Sana Agents provide a seamless way to access all your company’s apps, knowledge, and data, enabli…',
            occupation_label: 'Backend-utvecklare',
          },
        ],
      },
    },
    {
      kind: 'tool',
      toolName: 'placeAds',
      toolCallId: 'mock-sthlm-ai-call-3',
      input: {
        ad_ids: ['30991050', '31290812', '31288284', '31284834', '31256366'],
        layout: 'grid',
        emphasis: 'none',
      },
      output: {
        accepted: true,
        ad_ids: ['30991050', '31290812', '31288284', '31284834', '31256366'],
        layout: 'grid',
        emphasis: 'none',
      },
    },
    {
      kind: 'text',
      content:
        ' Found 5 active roles. The strongest signal comes from AI Engineer at Umain AB, AI Enablement Engineer at Extenda Retail AB, Founding AI Engineer at Spiich Labs AB. Cards are on the canvas to the right. Click any card to expand the description.',
    },
  ],
} as const
