// AUTO-GENERATED by web/scripts/capture-mock-fixtures.ts
// Do not edit by hand. Re-run the script when the ads expire.

import type { MockScript } from '@/features/mock/scripts/types'

export const stockholmAiEngineeringScript: MockScript = {
  prompt: 'Show me Stockholm AI engineering roles',
  chipLabel: 'Show me Stockholm AI engineering roles',
  messageId: 'mock-message-sthlm-ai',
  profile:
    '# Profile\n\n- Senior AI engineer, 8 years experience\n- Strong in Python, PyTorch, Hugging Face, retrieval-augmented generation\n- Comfortable with production MLOps on AWS or GCP\n- Based in Stockholm, open to hybrid\n',
  steps: [
    {
      kind: 'text',
      content:
        'Looking up the JobTech taxonomy for AI engineering and Stockholm so the search query uses real concept ids.',
    },
    {
      kind: 'tool',
      toolName: 'lookupConcept',
      toolCallId: 'mock-sthlm-ai-call-1',
      input: {
        query: 'AI engineer Stockholm',
        top_k: 6,
      },
      output: {
        results: [
          {
            concept_id: 'hCMr_L4F_8hq',
            preferred_label: 'SQE Supplier Quality Engineer',
            type: 'occupation',
          },
          {
            concept_id: 'CifL_Rzy_Mku',
            preferred_label: 'Stockholms län',
            type: 'region',
          },
        ],
      },
    },
    {
      kind: 'text',
      content:
        ' Now searching live JobTech ads for AI engineering roles based in Stockholm.',
    },
    {
      kind: 'tool',
      toolName: 'searchJobs',
      toolCallId: 'mock-sthlm-ai-call-2',
      input: {
        query: 'AI engineer',
        top_k: 5,
      },
      output: {
        results: [
          {
            ad_id: '31429441',
            headline: 'AI Engineer',
            employer_name: 'SAVR AB',
            municipality: 'Stockholm',
            application_deadline: '2027-03-01T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31429441',
            description_excerpt:
              'SAVR is a fast-growing Swedish fintech company on a mission to reinvent investing. We empower investors with a platform that offers lower fees, greater transparency, and a radically improved experience. We’re not just building another investment service — we’re reimagining how financial products should work for people, not just institutions. As part of our ambitious, innovative and curious team, you’ll help shape the future of investing in Sweden and beyond. A quick note: Thi…',
            occupation_label: 'Mjukvaruutvecklare',
          },
          {
            ad_id: '30991050',
            headline: 'AI Engineer',
            employer_name: 'Umain AB',
            municipality: 'Stockholm',
            application_deadline: '2026-10-31T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/30991050',
            description_excerpt:
              "At Umain, we're not just creating software; we're crafting the future, one innovative project at a time. With our motto \"Shape, Ship, Scale,\" we empower our team to not only envision the future but also play a pivotal role in building it. We're a dynamic team where you can shape the future, ship groundbreaking solutions, and scale your abilities in many different ways. We're on the lookout for developers ready to join us in this journey, bringing passion, creativity, and dedi…",
            occupation_label: 'Mjukvaruutvecklare',
          },
          {
            ad_id: '31420374',
            headline: 'AI Software Engineer',
            employer_name: 'Jobway AB',
            municipality: 'Stockholm',
            application_deadline: '2026-09-25T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31420374',
            description_excerpt:
              'Är du en utvecklare som gärna bygger hela lösningen från idé till färdig produkt? Brinner du för AI, modern teknik och att ligga i framkant av utvecklingen? Då kan detta vara möjligheten för dig! Ansök redan idag! I rollen som AI Software Engineer hos Qrendo blir du en viktig del av ett litet, snabbfotat produktteam där du får arbeta med den senaste tekniken inom AI och mjukvaruutveckling. Du kommer att vara med och vidareutveckla ReqAI, ett AI-drivet kravhanteringssystem som…',
            occupation_label: 'Systemutvecklare/Programmerare',
          },
          {
            ad_id: '31485568',
            headline: 'Senior AI Engineer',
            employer_name: 'PLAYipp AB',
            municipality: 'Gävle',
            application_deadline: '2027-03-15T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31485568',
            description_excerpt:
              "We're looking for a Senior AI Engineer Join us in transforming the digital signage landscape. PLAYipp, the leading Nordic digital signage company, is seeking a senior engineer to own features end-to-end — from PRD to Production — which increasingly include building AI capabilities directly into our product. At PLAYipp, we don't write code by hand — everything is built by directing AI coding tools (we use Claude Code), and you're fully accountable for what ships, however it wa…",
            occupation_label: 'Fullstack-utvecklare',
          },
          {
            ad_id: '31475629',
            headline: 'AI Solutions Engineer',
            employer_name: 'AuraGroup AB',
            municipality: 'Stockholm',
            application_deadline: '2027-03-13T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31475629',
            description_excerpt:
              'Build AI that works in the real world We are looking for an AI Solutions Engineer who wants to build AI solutions that work inside client environments, pass their security reviews and keep running after the project closes. This is not about prototypes or pilots. It is about getting solutions into production, connected to the systems clients actually use. The role You will work alongside our AI engineers and transformation strategists to design, build and deploy agentic soluti…',
            occupation_label: 'Dataingenjör',
          },
        ],
      },
    },
    {
      kind: 'tool',
      toolName: 'placeAds',
      toolCallId: 'mock-sthlm-ai-call-3',
      input: {
        ad_ids: ['31429441', '30991050', '31420374', '31485568', '31475629'],
        layout: 'grid',
        emphasis: 'none',
      },
      output: {
        accepted: true,
        ad_ids: ['31429441', '30991050', '31420374', '31485568', '31475629'],
        layout: 'grid',
        emphasis: 'none',
      },
    },
    {
      kind: 'text',
      content:
        ' Found 5 active roles. The strongest signal comes from AI Engineer at SAVR AB, AI Engineer at Umain AB, AI Software Engineer at Jobway AB. Cards are on the canvas to the right. Click any card to expand the description.',
    },
  ],
} as const
