// AUTO-GENERATED by web/scripts/capture-mock-fixtures.ts
// Do not edit by hand. Re-run the script when the ads expire.

import type { MockScript } from '@/features/mock/scripts/types'

export const stockholmNursingScript: MockScript = {
  prompt: 'Find Stockholm nursing roles ranked against my profile',
  chipLabel: 'Find Stockholm nursing roles ranked against my profile',
  messageId: 'mock-message-sthlm-nursing',
  profile:
    '# Profile\n\n- Registered nurse, 6 years on acute wards\n- Specialist training in cardiology\n- Swedish and English fluent\n- Based in Stockholm, weekday shifts preferred\n',
  steps: [
    {
      kind: 'text',
      content:
        'Resolving "nurse" and "Stockholm" against the JobTech taxonomy so the search hits the right occupation family.',
    },
    {
      kind: 'tool',
      toolName: 'lookupConcept',
      toolCallId: 'mock-sthlm-nursing-call-1',
      input: {
        query: 'sjuksköterska Stockholm',
        top_k: 8,
      },
      output: {
        results: [
          {
            concept_id: 'bXNH_MNX_dUR',
            preferred_label: 'Sjuksköterska, grundutbildad',
            type: 'occupation',
          },
          {
            concept_id: 'uaJs_9YA_Cnp',
            preferred_label: 'Sjuksköterska, äldreomsorg och -vård/geriatrik',
            type: 'occupation',
          },
          {
            concept_id: '4KeX_GcW_9jY',
            preferred_label: 'Sjuksköterska, medicin och kirurgi',
            type: 'occupation',
          },
          {
            concept_id: 'kHno_7rL_Lcm',
            preferred_label: 'Sjuksköterska, geriatrisk vård',
            type: 'occupation',
          },
          {
            concept_id: 'hbyN_1pA_VxX',
            preferred_label: 'Medicinskt ansvarig sjuksköterska',
            type: 'occupation',
          },
          {
            concept_id: 'CifL_Rzy_Mku',
            preferred_label: 'Stockholms län',
            type: 'region',
          },
        ],
      },
    },
    {
      kind: 'text',
      content: ' Searching live nursing roles in the Stockholm region.',
    },
    {
      kind: 'tool',
      toolName: 'searchJobs',
      toolCallId: 'mock-sthlm-nursing-call-2',
      input: {
        query: 'sjuksköterska Stockholm',
        top_k: 5,
      },
      output: {
        results: [
          {
            ad_id: '31434274',
            headline: 'Almia söker sjuksköterska till Stockholm',
            employer_name: 'Almia AB',
            municipality: 'Stockholm',
            application_deadline: '2026-09-13T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31434274',
            description_excerpt:
              'Gör det som du älskar, som konsult! Kvalifikationer Vi söker dig med minst två års erfarenhet. Vi ser gärna att du som konsult har god samarbetsförmåga, är noggrann, och ansvarstagande. Arbetsuppgifter Sedvanliga arbetsuppgifter som Leg. Sjuksköterska med erfarenhet från {{department}}. Finner du tjänsten som Leg. Sjuksköterska till Stockholm intressant är du är varmt välkommen att höra av dig direkt till Amanda Aletto eller någon av hennes kollegor på rekrytering@almia.se el…',
            occupation_label: 'Sjuksköterska, grundutbildad',
          },
          {
            ad_id: '31422642',
            headline: 'Sjuksköterska sökes till hemsjukvård Stockholm',
            employer_name: 'Dedicare AB (publ)',
            municipality: 'Stockholm',
            application_deadline: '2026-09-30T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31422642',
            description_excerpt:
              'Dedicare är ett av Nordens största rekryterings- och bemanningsföretag inom vård och socialt arbete med verksamhet i Sverige, Norge, Finland och Danmark. Dedicare bemannar och rekryterar läkare, sjuksköterskor och socionomer till kunder i både privat och offentlig verksamhet. Koncernen är noterat på Nasdaq Stockholm sedan maj 2011. Dedicare är medlem i Almega Kompetensföretagen och har därmed kollektivavtal för alla anställda. Dedicare är kvalitetscertifierat enligt ISO 9001:…',
            occupation_label: 'Sjuksköterska, grundutbildad',
          },
          {
            ad_id: '31339409',
            headline: 'Sjuksköterska till kranskommun till Stockholm',
            employer_name: 'OFELIA VÅRD AB',
            municipality: 'Södertälje',
            application_deadline: '2026-09-14T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31339409',
            description_excerpt:
              'Ofelia Vård AB är tillsammans med Skandinavisk Hälsovård, Svensk Närsjukvård, Doc Care, HLR Landslaget och Linguacom, en del av Skandinavisk Hälsovård Group. Vi söker för kunds räkning sjuksköterska. Uppdraget gäller från omgående och under hösten. Ofelia Vård är ett auktoriserat bemanningsföretag med medlemskap i Kompetensföretagen. Med detta följer en garanti på att vi följer arbetsmarknadens lagar och regler. Vi har kollektivavtal med Vårdförbundet, Läkarförbundet och Unio…',
            occupation_label: 'Sjuksköterska, grundutbildad',
          },
          {
            ad_id: '30879803',
            headline: 'Legitimerad Sjuksköterska Sökes till Stockholm',
            employer_name: 'Omsorg & Behandling 1 AB',
            municipality: 'Stockholm',
            application_deadline: '2026-09-08T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/30879803',
            description_excerpt:
              'Välkommen till Omsorg & Behandling! Just nu söker vi leg.sjuksköterskor men även ni som är specialistutbildade till vårat team. Omsorg & Behandling är ett auktoriserat bemanningsföretag för Sveriges regioner, kommuner och privata vårdgivare. Vi är ett bemanningsföretag som är aktiva i hela Sverige . Våra konsultchefer i företaget är Sjuksköterskor med lång erfarenhet från vården och arbetar aktivt ute hos våra kunder.Kollektivavtal: Vi är medlem i Tjänsteföretagens Arbetsgiva…',
            occupation_label: 'Sjuksköterska, grundutbildad',
          },
          {
            ad_id: '31441913',
            headline: 'Vi söker sjuksköterska till HSL/LSS-teamet Stockholm',
            employer_name: 'Attendo Sverige AB',
            municipality: 'Stockholm',
            application_deadline: '2027-03-03T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31441913',
            description_excerpt:
              'Välkommen till en värderingsstyrd organisation Vill du vara med och bygga framtidens LSS-vård? Nu har du chansen att bli en del av vårt kompetenta och engagerade team! Vi är ett arbetslag med sjuksköterskor och ett eget rehabteam – och nu söker vi en sjuksköterska till våra LSS boenden i Stockholm. Beskrivning av tjänsten: Tillsammans med kollegor inom olika professioner och externa vårdkontakter arbetar du för att skapa den bästa möjliga vården – alltid med patienten i fokus…',
            occupation_label: 'Sjuksköterska, grundutbildad',
          },
        ],
      },
    },
    {
      kind: 'tool',
      toolName: 'groupAds',
      toolCallId: 'mock-sthlm-nursing-call-3',
      input: {
        groups: [
          {
            label: 'Strong fit',
            ad_ids: ['31434274', '31422642'],
          },
          {
            label: 'Consider',
            ad_ids: ['31339409', '30879803'],
          },
          {
            label: 'Worth a look',
            ad_ids: ['31441913'],
          },
        ],
      },
      output: {
        accepted: true,
        groups: [
          {
            label: 'Strong fit',
            ad_ids: ['31434274', '31422642'],
          },
          {
            label: 'Consider',
            ad_ids: ['31339409', '30879803'],
          },
          {
            label: 'Worth a look',
            ad_ids: ['31441913'],
          },
        ],
      },
    },
    {
      kind: 'tool',
      toolName: 'connectProfileToAds',
      toolCallId: 'mock-sthlm-nursing-call-4',
      input: {
        links: [
          {
            ad_id: '31434274',
            score: 0.92,
            rationale:
              'Cardiology specialist scope aligns with the profile training.',
          },
          {
            ad_id: '31422642',
            score: 0.8,
            rationale:
              'Acute-ward responsibility matches the experience in the profile.',
          },
          {
            ad_id: '31339409',
            score: 0.68,
            rationale:
              'Generalist nursing role that the profile experience covers.',
          },
          {
            ad_id: '30879803',
            score: 0.56,
            rationale:
              'Generalist nursing role that the profile experience covers.',
          },
        ],
      },
      output: {
        accepted: true,
        links: [
          {
            ad_id: '31434274',
            score: 0.92,
            rationale:
              'Cardiology specialist scope aligns with the profile training.',
          },
          {
            ad_id: '31422642',
            score: 0.8,
            rationale:
              'Acute-ward responsibility matches the experience in the profile.',
          },
          {
            ad_id: '31339409',
            score: 0.68,
            rationale:
              'Generalist nursing role that the profile experience covers.',
          },
          {
            ad_id: '30879803',
            score: 0.56,
            rationale:
              'Generalist nursing role that the profile experience covers.',
          },
        ],
      },
    },
    {
      kind: 'text',
      content:
        ' Grouped 5 roles by fit and drew weighted edges from the saved profile. The strong-fit tier carries the highest match scores. Each edge from the profile node carries a one-line rationale.',
    },
  ],
} as const
