// AUTO-GENERATED by web/scripts/capture-mock-fixtures.ts
// Do not edit by hand. Re-run the script when the ads expire.

import type { MockScript } from '@/features/mock/scripts/types'

export const stockholmNursingScript: MockScript = {
  prompt: 'Find Stockholm nursing roles ranked against my profile',
  chipLabel: 'Find Stockholm nursing roles ranked against my profile',
  messageId: 'mock-message-sthlm-nursing',
  profile:
    '# Profile\n\n- Registered nurse, 6 years on acute wards\n- Specialist training in cardiology\n- Swedish and English fluent\n- Based in Stockholm, weekday shifts preferred\n',
  steps: [
    {
      kind: 'text',
      content:
        'Resolving "nurse" and "Stockholm" against the JobTech taxonomy so the search hits the right occupation family.',
    },
    {
      kind: 'tool',
      toolName: 'lookupConcept',
      toolCallId: 'mock-sthlm-nursing-call-1',
      input: {
        query: 'sjuksköterska Stockholm',
        top_k: 8,
      },
      output: {
        results: [
          {
            concept_id: 'HdXc_PNB_pcU',
            preferred_label: 'Sjuksköterska, barnavårdscentral',
            type: 'occupation',
          },
          {
            concept_id: 'bXNH_MNX_dUR',
            preferred_label: 'Sjuksköterska, grundutbildad',
            type: 'occupation',
          },
          {
            concept_id: 'uaJs_9YA_Cnp',
            preferred_label: 'Sjuksköterska, äldreomsorg och -vård/geriatrik',
            type: 'occupation',
          },
          {
            concept_id: 'kHno_7rL_Lcm',
            preferred_label: 'Sjuksköterska, geriatrisk vård',
            type: 'occupation',
          },
          {
            concept_id: 'hbyN_1pA_VxX',
            preferred_label: 'Medicinskt ansvarig sjuksköterska',
            type: 'occupation',
          },
          {
            concept_id: 'CifL_Rzy_Mku',
            preferred_label: 'Stockholms län',
            type: 'region',
          },
        ],
      },
    },
    {
      kind: 'text',
      content: ' Searching live nursing roles in the Stockholm region.',
    },
    {
      kind: 'tool',
      toolName: 'searchJobs',
      toolCallId: 'mock-sthlm-nursing-call-2',
      input: {
        query: 'sjuksköterska Stockholm',
        top_k: 5,
      },
      output: {
        results: [
          {
            ad_id: '31376391',
            headline: 'Sjuksköterska i Stockholm',
            employer_name: 'VårdIX AB',
            municipality: 'Stockholm',
            application_deadline: '2026-08-30T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31376391',
            description_excerpt:
              'Hitta ditt nästa uppdrag med VårdIX-Bemanning På VårdIX-Bemanning tror vi att de bästa resultaten skapas när våra konsulter känner sig trygga, uppskattade och väl omhändertagna. Vi bygger långsiktiga relationer med våra sjuksköterskor och finns med som ett personligt stöd före, under och efter varje uppdrag. För oss handlar bemanning om mer än att matcha kompetens – det handlar om att hitta rätt uppdrag för rätt person och skapa ett samarbete som håller över tid. Nu söker vi…',
            occupation_label: 'Sjuksköterska, grundutbildad',
          },
          {
            ad_id: '31376296',
            headline: 'Sjuksköterska i Stockholm',
            employer_name: 'VårdIX AB',
            municipality: 'Stockholm',
            application_deadline: '2026-08-24T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31376296',
            description_excerpt:
              'Hitta ditt nästa uppdrag med VårdIX-Bemanning På VårdIX-Bemanning tror vi att de bästa resultaten skapas när våra konsulter känner sig trygga, uppskattade och väl omhändertagna. Vi bygger långsiktiga relationer med våra sjuksköterskor och finns med som ett personligt stöd före, under och efter varje uppdrag. För oss handlar bemanning om mer än att matcha kompetens – det handlar om att hitta rätt uppdrag för rätt person och skapa ett samarbete som håller över tid. Nu söker vi…',
            occupation_label: 'Sjuksköterska, grundutbildad',
          },
          {
            ad_id: '31339409',
            headline: 'Sjuksköterska till kranskommun till Stockholm',
            employer_name: 'OFELIA VÅRD AB',
            municipality: 'Södertälje',
            application_deadline: '2026-09-14T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31339409',
            description_excerpt:
              'Ofelia Vård AB är tillsammans med Skandinavisk Hälsovård, Svensk Närsjukvård, Doc Care, HLR Landslaget och Linguacom, en del av Skandinavisk Hälsovård Group. Vi söker för kunds räkning sjuksköterska. Uppdraget gäller från omgående och under hösten. Ofelia Vård är ett auktoriserat bemanningsföretag med medlemskap i Kompetensföretagen. Med detta följer en garanti på att vi följer arbetsmarknadens lagar och regler. Vi har kollektivavtal med Vårdförbundet, Läkarförbundet och Unio…',
            occupation_label: 'Sjuksköterska, grundutbildad',
          },
          {
            ad_id: '31092227',
            headline: 'Sjuksköterska inom vårdförsäkring i Stockholm',
            employer_name: 'The Finance Family AB',
            municipality: 'Stockholm',
            application_deadline: '2026-08-31T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31092227',
            description_excerpt:
              'The Finance Family söker nu efter en sjuksköterska för ett uppdrag i Stockholm. Tjänsten startar som ett konsultuppdrag, med möjlighet till förlängning efter uppdragets slut. Preliminär start augusti/september 2026 och t o m 30 april 2027 (initialt). Om rollen och arbetsuppgifter: Som sjuksköterska hos vår kund inom vårdförsäkring, blir du en del av ett större team som ansvarar för hanteringen av bolagets kunders försäkringsärenden. Du stödjer dig på gällande försäkringsvillk…',
            occupation_label: 'Sjuksköterska, grundutbildad',
          },
          {
            ad_id: '30879803',
            headline: 'Legitimerad Sjuksköterska Sökes till Stockholm',
            employer_name: 'Omsorg & Behandling 1 AB',
            municipality: 'Stockholm',
            application_deadline: '2026-08-25T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/30879803',
            description_excerpt:
              'Välkommen till Omsorg & Behandling! Just nu söker vi leg.sjuksköterskor men även ni som är specialistutbildade till vårat team. Omsorg & Behandling är ett auktoriserat bemanningsföretag för Sveriges regioner, kommuner och privata vårdgivare. Vi är ett bemanningsföretag som är aktiva i hela Sverige . Våra konsultchefer i företaget är Sjuksköterskor med lång erfarenhet från vården och arbetar aktivt ute hos våra kunder.Kollektivavtal: Vi är medlem i Tjänsteföretagens Arbetsgiva…',
            occupation_label: 'Sjuksköterska, grundutbildad',
          },
        ],
      },
    },
    {
      kind: 'tool',
      toolName: 'groupAds',
      toolCallId: 'mock-sthlm-nursing-call-3',
      input: {
        groups: [
          {
            label: 'Strong fit',
            ad_ids: ['31376391', '31376296'],
          },
          {
            label: 'Consider',
            ad_ids: ['31339409', '31092227'],
          },
          {
            label: 'Worth a look',
            ad_ids: ['30879803'],
          },
        ],
      },
      output: {
        accepted: true,
        groups: [
          {
            label: 'Strong fit',
            ad_ids: ['31376391', '31376296'],
          },
          {
            label: 'Consider',
            ad_ids: ['31339409', '31092227'],
          },
          {
            label: 'Worth a look',
            ad_ids: ['30879803'],
          },
        ],
      },
    },
    {
      kind: 'tool',
      toolName: 'connectProfileToAds',
      toolCallId: 'mock-sthlm-nursing-call-4',
      input: {
        links: [
          {
            ad_id: '31376391',
            score: 0.92,
            rationale:
              'Cardiology specialist scope aligns with the profile training.',
          },
          {
            ad_id: '31376296',
            score: 0.8,
            rationale:
              'Acute-ward responsibility matches the experience in the profile.',
          },
          {
            ad_id: '31339409',
            score: 0.68,
            rationale:
              'Generalist nursing role that the profile experience covers.',
          },
          {
            ad_id: '31092227',
            score: 0.56,
            rationale:
              'Generalist nursing role that the profile experience covers.',
          },
        ],
      },
      output: {
        accepted: true,
        links: [
          {
            ad_id: '31376391',
            score: 0.92,
            rationale:
              'Cardiology specialist scope aligns with the profile training.',
          },
          {
            ad_id: '31376296',
            score: 0.8,
            rationale:
              'Acute-ward responsibility matches the experience in the profile.',
          },
          {
            ad_id: '31339409',
            score: 0.68,
            rationale:
              'Generalist nursing role that the profile experience covers.',
          },
          {
            ad_id: '31092227',
            score: 0.56,
            rationale:
              'Generalist nursing role that the profile experience covers.',
          },
        ],
      },
    },
    {
      kind: 'text',
      content:
        ' Grouped 5 roles by fit and drew weighted edges from the saved profile. The strong-fit tier carries the highest match scores. Each edge from the profile node carries a one-line rationale.',
    },
  ],
} as const
