// AUTO-GENERATED by web/scripts/capture-mock-fixtures.ts
// Do not edit by hand. Re-run the script when the ads expire.

import type { MockScript } from '@/features/mock/scripts/types'

export const stockholmAiEngineeringScript: MockScript = {
  prompt: 'Show me Stockholm AI engineering roles',
  chipLabel: 'Show me Stockholm AI engineering roles',
  messageId: 'mock-message-sthlm-ai',
  profile:
    '# Profile\n\n- Senior AI engineer, 8 years experience\n- Strong in Python, PyTorch, Hugging Face, retrieval-augmented generation\n- Comfortable with production MLOps on AWS or GCP\n- Based in Stockholm, open to hybrid\n',
  steps: [
    {
      kind: 'text',
      content:
        'Looking up the JobTech taxonomy for AI engineering and Stockholm so the search query uses real concept ids.',
    },
    {
      kind: 'tool',
      toolName: 'lookupConcept',
      toolCallId: 'mock-sthlm-ai-call-1',
      input: {
        query: 'AI engineer Stockholm',
        top_k: 6,
      },
      output: {
        results: [
          {
            concept_id: 'hCMr_L4F_8hq',
            preferred_label: 'SQE Supplier Quality Engineer',
            type: 'occupation',
          },
          {
            concept_id: 'CifL_Rzy_Mku',
            preferred_label: 'Stockholms län',
            type: 'region',
          },
        ],
      },
    },
    {
      kind: 'text',
      content:
        ' Now searching live JobTech ads for AI engineering roles based in Stockholm.',
    },
    {
      kind: 'tool',
      toolName: 'searchJobs',
      toolCallId: 'mock-sthlm-ai-call-2',
      input: {
        query: 'AI engineer',
        top_k: 5,
      },
      output: {
        results: [
          {
            ad_id: '31429441',
            headline: 'AI Engineer',
            employer_name: 'SAVR AB',
            municipality: 'Stockholm',
            application_deadline: '2027-03-01T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31429441',
            description_excerpt:
              'SAVR is a fast-growing Swedish fintech company on a mission to reinvent investing. We empower investors with a platform that offers lower fees, greater transparency, and a radically improved experience. We’re not just building another investment service — we’re reimagining how financial products should work for people, not just institutions. As part of our ambitious, innovative and curious team, you’ll help shape the future of investing in Sweden and beyond. A quick note: Thi…',
            occupation_label: 'Mjukvaruutvecklare',
          },
          {
            ad_id: '30991050',
            headline: 'AI Engineer',
            employer_name: 'Umain AB',
            municipality: 'Stockholm',
            application_deadline: '2026-10-31T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/30991050',
            description_excerpt:
              "At Umain, we're not just creating software; we're crafting the future, one innovative project at a time. With our motto \"Shape, Ship, Scale,\" we empower our team to not only envision the future but also play a pivotal role in building it. We're a dynamic team where you can shape the future, ship groundbreaking solutions, and scale your abilities in many different ways. We're on the lookout for developers ready to join us in this journey, bringing passion, creativity, and dedi…",
            occupation_label: 'Mjukvaruutvecklare',
          },
          {
            ad_id: '31420374',
            headline: 'AI Software Engineer',
            employer_name: 'Jobway AB',
            municipality: 'Stockholm',
            application_deadline: '2026-09-25T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31420374',
            description_excerpt:
              'Är du en utvecklare som gärna bygger hela lösningen från idé till färdig produkt? Brinner du för AI, modern teknik och att ligga i framkant av utvecklingen? Då kan detta vara möjligheten för dig! Ansök redan idag! I rollen som AI Software Engineer hos Qrendo blir du en viktig del av ett litet, snabbfotat produktteam där du får arbeta med den senaste tekniken inom AI och mjukvaruutveckling. Du kommer att vara med och vidareutveckla ReqAI, ett AI-drivet kravhanteringssystem som…',
            occupation_label: 'Systemutvecklare/Programmerare',
          },
          {
            ad_id: '31472123',
            headline: 'AI Platform Engineer',
            employer_name: 'Nordea Bank Abp, filial i Sverige',
            municipality: 'Stockholm',
            application_deadline: '2026-09-24T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31472123',
            description_excerpt:
              'Job ID: 3525 We are looking for an AI Platform Engineer to drive the development and adoption of AI-powered solutions that strengthen our ability to detect and investigate financial crime. The role is permanent and can be based in Helsinki, Tallinn, Poland or Stockholm. About our team Meet the Data and Platform Team. Our role is to improve how we detect and investigate financial crime with the help of AI and machine learning to keep our customers, Nordea and society safe. Our…',
            occupation_label: 'IT-arkitekt',
          },
          {
            ad_id: '31469989',
            headline: 'Senior AI Engineer',
            employer_name: 'Rasulson Consulting AB',
            municipality: 'Stockholm',
            application_deadline: '2026-09-16T23:59:59',
            webpage_url:
              'https://arbetsformedlingen.se/platsbanken/annonser/31469989',
            description_excerpt:
              "Role We're looking for a senior AI Engineer for a consulting assignment focused on building AI-driven capabilities in a business-critical, quality-sensitive setting for a company within healthcare/medtech. Responsibilities Build AI functions that turn clinical content into practical, actionable suggestions for therapists in their daily work. Design end-to-end pipelines, including prompt and chain architectures, with structured outputs broken into clear, independently testable…",
            occupation_label: 'Systemansvarig',
          },
        ],
      },
    },
    {
      kind: 'tool',
      toolName: 'placeAds',
      toolCallId: 'mock-sthlm-ai-call-3',
      input: {
        ad_ids: ['31429441', '30991050', '31420374', '31472123', '31469989'],
        layout: 'grid',
        emphasis: 'none',
      },
      output: {
        accepted: true,
        ad_ids: ['31429441', '30991050', '31420374', '31472123', '31469989'],
        layout: 'grid',
        emphasis: 'none',
      },
    },
    {
      kind: 'text',
      content:
        ' Found 5 active roles. The strongest signal comes from AI Engineer at SAVR AB, AI Engineer at Umain AB, AI Software Engineer at Jobway AB. Cards are on the canvas to the right. Click any card to expand the description.',
    },
  ],
} as const
